<a href="https://colab.research.google.com/github/Mani512996/pocs/blob/main/twitterentiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 3.2 MB/s 
     |████████████████████████████████| 101 kB 11.4 MB/s 
     |████████████████████████████████| 6.6 MB 42.1 MB/s 
     |████████████████████████████████| 596 kB 55.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
!pip install scipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
from transformers import AutoTokenizer, AutoModelForMaskedLM, AutoModelForSequenceClassification


In [6]:
from scipy.special import softmax

In [7]:
tweet = '@manikandan today is cold at home'

In [8]:
tweet_words = []

In [9]:
from transformers import pipeline

In [10]:
import torch

In [11]:
import torch.nn.functional as F

In [24]:
model_name = 'distilbert-base-uncased-finetuned-sst-2-english'
classifier = pipeline("sentiment-analysis", model = model_name)

In [36]:
results = classifier(['we are very happy to show  you the 😍 transformers library.',
                     'we hope you  hate it'])

In [37]:
for result in results:
  print(result)

{'label': 'POSITIVE', 'score': 0.9997795224189758}
{'label': 'NEGATIVE', 'score': 0.9994296431541443}


In [39]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [45]:
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [46]:
model_name = 'distilbert-base-uncased-finetuned-sst-2-english'
classifier = pipeline("sentiment-analysis", model = model_name)

In [47]:
results = classifier(['we are very happy to show  you the 😍 transformers library.',
                     'we hope you  hate it'])

In [48]:
for result in results:
  print(result)

{'label': 'POSITIVE', 'score': 0.9997795224189758}
{'label': 'NEGATIVE', 'score': 0.9994296431541443}


In [49]:
#tokenizer functions
tokens = tokenizer.tokenize('we are very happy to show  you the 😍 transformers library.',
                     'we hope you  hate it')
token_ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = tokenizer('we are very happy to show  you the 😍 transformers library.',
                     'we hope you  hate it')



In [50]:
print(tokens)
print(token_ids)
print(input_ids)

['we', 'are', 'very', 'happy', 'to', 'show', 'you', 'the', '[UNK]', 'transformers', 'library', '.', 'we', 'hope', 'you', 'hate', 'it']
[2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012, 2057, 3246, 2017, 5223, 2009]
{'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012, 102, 2057, 3246, 2017, 5223, 2009, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [56]:
x_train = ('we are very happy to show  you the 😍 transformers library')        
batch = tokenizer(x_train, padding=True, truncation=True, max_length=512, return_tensors='pt')
print(batch)

{'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996,   100,
         19081,  3075,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [57]:
with torch.no_grad():
  outputs = model(**batch)


In [58]:
print(outputs)

SequenceClassifierOutput(loss=None, logits=tensor([[-4.0624,  4.3069]]), hidden_states=None, attentions=None)


In [60]:
predictions = F.softmax(outputs.logits, dim=1)
print(predictions)
labels = torch.argmax(predictions, dim=1)
print(labels)
labels = [model.config.id2label[label_id] for label_id in labels.tolist()]

tensor([[2.3183e-04, 9.9977e-01]])
tensor([1])


In [61]:
print(labels)

['POSITIVE']


In [64]:
#save_directory = 'saved'
#tokenizer.save_pretrained(save_directory)
#model.save_pretrained(save_directory)

('saved/tokenizer_config.json',
 'saved/special_tokens_map.json',
 'saved/vocab.txt',
 'saved/added_tokens.json',
 'saved/tokenizer.json')

In [70]:
model_name = 'oliverguhr/german-sentiment-bert'

In [71]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained((model_name))

In [75]:
x_train_german = [
    "Mit keinem guten Ergebniss","Das ist gar nicht mal so gut",
    "Total awesome!","nicht so schlecht wie erwartet",
    "Der Test verlief positiv.","Sie fährt ein grünes Auto."]

In [76]:
batch = tokenizer(x_train_german, padding=True, truncation=True, max_length=512, return_tensors='pt')
with torch.no_grad():
  outputs = model(**batch)
  label_ids = torch.argmax(outputs.logits, dim=1)
  print(label_ids)
  labels = [model.config.id2label[label_id] for label_id in label_ids.tolist()]
  print(labels)

tensor([1, 1, 0, 0, 2, 2])
['negative', 'negative', 'positive', 'positive', 'neutral', 'neutral']


In [77]:
print(batch)

{'input_ids': tensor([[    3,   304,  8524,  5569,  2011, 26902,     4,     0,     0],
        [    3,   295,   127,  2523,   149,  2723,   181,  1522,     4],
        [    3, 19990,    18,  7117,  4741, 26982,     4,     0,     0],
        [    3,   149,   181,  6975,   246,  6303,     4,     0,     0],
        [    3,   233,  4496, 14332,  8453, 26914,     4,     0,     0],
        [    3,   371,  9755,    39, 19044, 26902,  3512, 26914,     4]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])}
